analysis_dict={ #old
    'DARK_CURRENT_PD':'DARK_RFPD',
    'FORWARD_VOLTAGE_PD':'FWD_RFPD',

    'SERIES_RESISTANCE_5MA':'SERIES_RESISTANCE_5MA',
    'SERIES_RESISTANCE_10MA':'SERIES_RESISTANCE_10MA',

    'EAM_ANALYSIS':'OWEAM_REV_',

    'MZM_ANALYSIS_REV':'OWEOPM_REV',
    'MZM_ANALYSIS_FWD':'OWEOPM_FWD',

    'FORWARD_VOLTAGE_EAM':'EAM_FWD',
    'LEAKAGE_CURRENT_EAM':'EAM_REV',

    'FORWARD_VOLTAGE_EOPM':'EOPMfwd',
    'LEAKAGE_CURRENT_EOPM':'EOPMrev',

    
    'LIV_EAM_DBRLASER':'LIV_EAMDBR',
    
    'LIV_FP_LASER':'LIV_FP',
    'LIV_FP_LASER_4P':'LIV_FP_4P', #does not yet exist
    
    'LIV_EOPM_DBRLASER':'LIV_OWEOPM',
    }

analysis_dict_v2={
    'DARK_CURRENT_PD':'LEAKAGE_CURRENT_2_5',
    'LEAKAGE_CURRENT_2_5_OFFSET':'LEAKAGE_CURRENT_2_5_OFFSET',
    'FORWARD_VOLTAGE_PD':'FORWARD_VOLTAGE_1MA',
    
    'FORWARD_VOLTAGE_1MA':'FORWARD_VOLTAGE_1MA',
    'FORWARD_VOLTAGE_10MA':'FORWARD_VOLTAGE_10MA',
    'FORWARD_VOLTAGE_20MA':'FORWARD_VOLTAGE_20MA',
    'FORWARD_VOLTAGE_300MA':'FORWARD_VOLTAGE_300MA',
    
    'SERIES_RESISTANCE_5MA':'SERIES_RESISTANCE_5MA',
    'SERIES_RESISTANCE_10MA':'SERIES_RESISTANCE_10MA',
    'SERIES_RESISTANCE_100MA':'SERIES_RESISTANCE_100MA',
    
    'EAM_ANALYSIS_REV':'EAM_ANALYSIS_REV',

    'MZM_ANALYSIS_REV':'MZM_ANALYSIS_REV',
    'MZM_ANALYSIS_FWD':'MZM_ANALYSIS_FWD',
    'MZM_ANALYSIS_REV_EXT':'MZM_ANALYSIS_REV_EXT',

    'FORWARD_VOLTAGE_EAM':'FORWARD_VOLTAGE_1MA',
    'LEAKAGE_CURRENT_EAM':'LEAKAGE_CURRENT_2_5_8',
    'LEAKAGE_CURRENT_2_5_8':'LEAKAGE_CURRENT_2_5_8',
    
    'LEAKAGE_CURRENT_5':'LEAKAGE_CURRENT_5',
    
    'FORWARD_VOLTAGE_EOPM':'FORWARD_VOLTAGE_1MA',
    'LEAKAGE_CURRENT_EOPM':'LEAKAGE_CURRENT_2_5',

    'LIV_DBR':'LIV_ANALYSIS',
    'LIV_EAM_DBRLASER':'LIV_ANALYSIS',
    
    'LIV_FP_LASER':'LIV_ANALYSIS',
    'LIV_GAGE':'LIV_GAGE_ANALYSIS',
    'LIV_FP_LASER_4P':'LIV_FP_4P', #does not yet exist
    
    'LIV_EOPM_DBRLASER':'LIV_ANALYSIS',
    'SLOPE_40':'SLOPE_40',
    
    'LEAKAGE_CURRENT_2_5':'LEAKAGE_CURRENT_2_5',
    'SPECTRUM_BT':'SPECTRUM',

    'PLATING_RESISTANCE':'CURRENT_OHMIC_RESISTANCE',
    'SERIES_RESISTANCE':'SERIES_RESISTANCE',
    'CURRENT_OHMIC_RESISTANCE':'CURRENT_OHMIC_RESISTANCE',
    # 'PLATING_RESISTANCE':'VOLTAGE_OHMIC_RESISTANCE',
    # 'OHMIC RESISTANCE':'OHMIC_RESISTANCE',
    'OHMIC_RESISTANCE_VOLTAGE':'TLM_VOLTAGE_OHMIC_RESISTANCE',
    'OHMIC_RESISTANCE_CURRENT':'TLM_CURRENT_OHMIC_RESISTANCE',
    'FORWARD_VOLTAGE_4P':'FORWARD_VOLTAGE',
    'FORWARD_VOLTAGE':'FORWARD_VOLTAGE',
    'LI_DBR':'LI_ANALYSIS'
    }


